import type { ChatProvider } from './ai';
export declare class AITerminalManager {
    private ip;
    private port;
    private terminal;
    private fitAddon;
    private webLinksAddon;
    private ws;
    private container;
    private resizeObserver;
    private styleElement;
    private _disposed;
    private currentTheme;
    private currentProvider;
    private outputHistory;
    private outputHistoryLength;
    onExit?: (code: number) => void;
    onError?: (message: string) => void;
    onRuntimeSession?: (runtimeSessionId: string, kind?: string) => void;
    onRuntimeCursor?: (cursor: number) => void;
    constructor(ip: string, port: number);
    mount(container: HTMLElement, theme: 'dark' | 'light', provider?: ChatProvider): void;
    remount(container: HTMLElement, theme: 'dark' | 'light', provider?: ChatProvider): void;
    connect(options: {
        provider: ChatProvider;
        prompt?: string;
        sessionId?: string;
        runtimeSessionId?: string;
        runtimeCursor?: number;
        cwd: string;
        model?: string;
    }): void;
    sendInput(data: string): void;
    fit(): void;
    private proposeDimensions;
    setTheme(theme: 'dark' | 'light'): void;
    focus(): void;
    clear(): void;
    write(data: string): void;
    private renderOutput;
    private getOverviewRulerWidth;
    private applyProviderLayout;
    private rememberOutput;
    private clearOutputHistory;
    private replayOutputHistory;
    closeWebSocket(): void;
    dispose(): void;
    isDisposed(): boolean;
    private attachTerminal;
    private detachTerminal;
    private injectCSS;
}
export declare function checkTerminalAvailable(ip: string, port: number): Promise<boolean>;
