export declare const LineName = "data-insp-row";
export declare const ColumnName = "data-insp-col";
export declare const PathName = "data-insp-path";
export declare const NodeName = "data-insp-node";
export declare const DefaultPort = 5678;
export declare const JsFileExtList: string[];
export declare const ViteVirtualModule_EliminateVueWarning = "virtual:code-inspector-plugin-eliminate-vue-warning-code";
export declare const ViteVirtualModule_Client = "virtual:code-inspector-plugin-client-code";
export declare const FormatFile = "{file}";
export declare const FormatLine = "{line}";
export declare const FormatColumn = "{column}";
export declare const DefaultPathFormat: string;
export declare const AstroToolbarFile = "\0astro:dev-toolbar";
